apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kollab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
      - name: setup-cache
        image: projet-backend:latest
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args:
          - -c
          - |
            mkdir -p /var/www/storage/framework/views
            mkdir -p /var/www/storage/framework/cache/data
            mkdir -p /var/www/storage/logs
            chmod -R 777 /var/www/storage
            chown -R www-data:www-data /var/www/storage
        volumeMounts:
        - name: storage-data
          mountPath: /var/www/storage
        - name: cache-data
          mountPath: /var/www/bootstrap/cache
      containers:
        - name: backend
          image: projet-backend:latest
          imagePullPolicy: Never
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_PASSWORD
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 20
          volumeMounts:
            - name: storage-data
              mountPath: /var/www/storage
            - name: cache-data
              mountPath: /var/www/bootstrap/cache
      volumes:
        - name: storage-data
          emptyDir: {}
        - name: cache-data
          emptyDir: {}
