apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: kollab
data:
  NEXT_PUBLIC_API_URL: "http://kollab.local/api"
  NEXT_PUBLIC_BACKEND_URL: "http://kollab.local"
  NODE_ENV: "production"
