apiVersion: batch/v1
kind: Job
metadata:
  name: db-reset
  namespace: kollab
spec:
  template:
    spec:
      containers:
      - name: db-reset
        image: ghcr.io/ismailacongombo/kollab/backend:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Resetting database..."
            sleep 10
            php artisan migrate:fresh --force
            echo "Database reset completed"
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD
      restartPolicy: OnFailure